# Generated by Django 4.2.4 on 2023-08-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depozit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('adresa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Raft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=10)),
                ('depozit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Depozit.depozit')),
            ],
        ),
    ]
